import React, { useState, useEffect } from 'react';
import CustomSelect from '../CustomSelect/CustomSelect';
import { resolveFileUrl } from '../../API';

const initialForm = {
  registerId: '',
  paymentType: '',
  amountReceived: '',
  receiptGen: '',
  nextIns: '',
  id: '',
};

const InstallDialogue = ({ setOpen, onSubmit, editData, stuRegs }) => {
  const [form, setForm] = useState(initialForm);

  // Pre-fill form on edit
  useEffect(() => {
    if (editData) {
      setForm({
        registerId: editData.registerId || editData.register?._id || '',
        paymentType: editData.paymentType,
        amountReceived: editData.amountReceived || editData.amountPaid,
        receiptGen: editData.receiptGen,
        nextIns: editData.nextIns ? String(editData.nextIns).slice(0, 10) : '',
        id: editData._id,
      });
    } else {
      setForm(initialForm);
    }
  }, [editData]);

  // Auto-fill receiptGen when selecting student (only if not editing and field is empty)
  useEffect(() => {
    if (!editData && form.registerId) {
      const selected = stuRegs.find((reg) => reg._id === form.registerId);
      if (selected) {
        setForm((prev) => ({
          ...prev,
          receiptGen: prev.receiptGen || selected.receiptGen || '',
        }));
      }
    }
  }, [form.registerId, editData, stuRegs]);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setForm((prev) => ({ ...prev, [name]: value }));
  };

  const handleSubmit = () => {
    const data = new FormData();
    Object.entries(form).forEach(([key, value]) => {
      if (value !== null) data.append(key, value);
    });
    onSubmit(data, !!editData);
  };

  const selectedReg = stuRegs.find((reg) => reg._id === form.registerId);

  return (
    <div className="popup">
      <div className="popup-content">
        <h2>{editData ? 'Edit Installment' : 'Add Installment'}</h2>

        <CustomSelect
          options={stuRegs
            ?.filter((v) => Number(v.balance) !== 0)
            .map((s) => ({
              value: s._id,
              label: `${s.student?.studentName} (${s.student?.studentRedId})`,
              image: resolveFileUrl(s.student?.studentImage),
            }))
          }
          selected={
            selectedReg && {
              value: selectedReg._id,
              label: `${selectedReg.student?.studentName} - ${selectedReg.course?.courseName}`,
              image: resolveFileUrl(selectedReg.student?.studentImage),
            }
          }
          onChange={(val) => setForm({ ...form, registerId: val })}
          placeholder="Select Student..."
        />

        <select name="paymentType" onChange={handleChange} value={form.paymentType}>
          <option value="">Select Payment Type...</option>
          <option value="Cash">Cash</option>
          <option value="UPI">UPI</option>
          <option value="Card">Card</option>
          <option value="Bank">Bank</option>
        </select>

        <input
          type="text"
          name="amountReceived"
          value={form.amountReceived}
          onChange={handleChange}
          placeholder="Amount Received..."
        />

      <input
          type="date"
          name="nextIns"
          value={form.nextIns}
          onChange={handleChange}
       
        />
        <input
          type="text"
          name="receiptGen"
          value={form.receiptGen}
          onChange={handleChange}
          placeholder="Receipt Generated By..."
        />

        <div className="dialogue-actions">
          <button
            onClick={handleSubmit}
            style={editData ? { background: '#007cdf', color: '#fff' } : { background: '#007bff', color: '#fff' }}
          >
            {editData ? 'Update' : 'Add'}
          </button>
          <button onClick={() => setOpen(false)}>Cancel</button>
        </div>
      </div>
    </div>
  );
};

export default InstallDialogue;
