// import React from 'react';
// import { Link } from 'react-router-dom';

// const StuInsTable = ({ stuIns, onEdit, onDelete }) => {
//   // Step 1: Group installments by student ID
//   const paymentTracker = {};

//   stuIns.forEach(p => {
//     const studentId = p.register?.student?._id;
//     const courseFees = parseFloat(p.register?.courseFees || 0);
//     const firstInstallment = parseFloat(p.register?.amountReceivedd || 0);
//     const nowPaid = parseFloat(p.amountReceived || 0);

//     if (!paymentTracker[studentId]) {
//       paymentTracker[studentId] = {
//         alreadyPaid: firstInstallment,
//         payments: []
//       };
//     }

//     const alreadyPaid = paymentTracker[studentId].alreadyPaid;
//     const totalPaidSoFar = alreadyPaid + nowPaid;
//     const balance = courseFees - totalPaidSoFar;

//     paymentTracker[studentId].payments.push({
//       ...p,
//       courseFees,
//       alreadyPaid,
//       nowPaid, 
//       totalPaidSoFar, 
//       balance 
//     });

//     // Update running total
//     paymentTracker[studentId].alreadyPaid = totalPaidSoFar;
//   });

//   // Flatten for rendering
//   const flattenedPayments = Object.values(paymentTracker)
//     .flatMap(group => group.payments);

//   return (
//     <div className='staff-table-container'>
//       <table className='staff-table'>
//         <thead>
//           <tr>
//             <th>Bill Id</th>
//             <th>Student Id</th>
//             <th>Name</th>
//             <th>Image</th>
//             <th>Course Fees</th>
//             <th>Already Paid</th>
//             <th>Now Paid</th>
//             <th>Total Paid So Far</th>
//             <th>Balance</th>
//             <th>Course Title</th>
//             <th>Receipt Generated By</th>
//             <th>Payment Mode</th>
//             <th>Duration</th>
//             <th>Freezing Date</th>
//             <th>Date</th>
//             <th>View</th>
//             <th>Actions</th>
//           </tr>
//         </thead>
//         <tbody>
//           {flattenedPayments.slice().reverse().map((p, i) => (
//             <tr key={p._id}>
//               <td>{i + 1}</td>
//               <td>{p.register?.student?.studentRedId}</td>
//               <td>{p.register?.student?.studentName}</td>
//               <td>
//                 <img
//                   src={`http://localhost:5000/uploads/${p.register?.student?.studentImage}`}
//                   width={30}
//                   height={30}
//                   alt="student"
//                 />
//               </td>
//               <td>{p.courseFees}</td>
//               <td>{p.alreadyPaid}</td>
//               <td>{p.nowPaid}</td>
//               <td>{p.totalPaidSoFar}</td>
//               <td>{p.balance}</td>
//               <td>{p.register?.course?.courseName}</td>
//               <td>{p.receiptGen}</td>
//               <td>{p.register?.paymentType}</td>
//               <td>{p.register?.courseDuration}</td>
//               <td>{p.register?.freezingDate}</td>
//               <td>{p.updatedAt?.slice(0, 10)}</td>
//               <td>
//                 <Link to={`/install/${p._id}/${i}/${p.nowPaid}/${p.totalPaidSoFar}/${p.balance}`}>👁️</Link>
//               </td>
//               <td>
//                 <button onClick={() => onEdit(p)} style={{ padding: '1px', marginRight: '5px' }}>✏️</button>
//                 <button onClick={() => onDelete(p._id)} style={{ padding: '1px', marginRight: '5px' }}>🗑️</button>
//               </td>
//             </tr>
//           ))}
//         </tbody>
//       </table>
//     </div>
//   );
// };

// export default StuInsTable;


import * as React from 'react';
import { DataGrid } from '@mui/x-data-grid';
import {
  Avatar,
  IconButton,
  Button,
  Typography,
  Paper
} from '@mui/material';
import { Edit, Delete } from '@mui/icons-material';
import { Link } from 'react-router-dom';
import { resolveFileUrl } from '../../API';

const StuInsTable = ({ stuIns, onEdit, onDelete }) => {
  // Step 1: Group installments by student ID
  const paymentTracker = {};

  stuIns.forEach(p => {
    const studentId = p.register?.student?._id;
    const courseFees = parseFloat(p.register?.courseFees || 0);
    const firstInstallment = parseFloat(p.register?.amountReceivedd || 0);
    const nowPaid = parseFloat(p.amountPaid || p.amountReceived || 0);

    if (!paymentTracker[studentId]) {
      paymentTracker[studentId] = {
        alreadyPaid: firstInstallment,
        payments: []
      };
    }

    const alreadyPaid = paymentTracker[studentId].alreadyPaid;
    const totalPaidSoFar = alreadyPaid + nowPaid;
    const balance = courseFees - totalPaidSoFar;

    paymentTracker[studentId].payments.push({
      ...p,
      courseFees,
      alreadyPaid,
      nowPaid,
      totalPaidSoFar,
      balance
    });

    paymentTracker[studentId].alreadyPaid = totalPaidSoFar;
  });

  // Flatten & reverse order for latest first
  const flattenedPayments = Object.values(paymentTracker)
    .flatMap(group => group.payments)
    .reverse();

  // Step 2: MUI DataGrid columns
  const columns = [
    {
      field: 'sno',
      headerName: 'Bill Id',
      width: 80,
      renderCell: (params) => params.api.getAllRowIds().indexOf(params.id) + 1,
      sortable: false,
      filterable: false,
    },
    { field: 'studentRedId', headerName: 'Student Id', width: 130 },
    { field: 'studentName', headerName: 'Name', width: 150 },
    {
      field: 'studentImage',
      headerName: 'Image',
      width: 80,
      renderCell: (params) =>
        params.row.studentImage ? (
          <Avatar
            src={resolveFileUrl(params.row.studentImage)}
            alt="student"
          />
        ) : (
          <Typography variant="body2" color="textSecondary">No Image</Typography>
        ),
      sortable: false,
      filterable: false,
    },
    { field: 'courseFees', headerName: 'Course Fees', width: 120 },
    { field: 'alreadyPaid', headerName: 'Already Paid', width: 120 },
    { field: 'nowPaid', headerName: 'Now Paid', width: 120 },
    { field: 'totalPaidSoFar', headerName: 'Total Paid So Far', width: 150 },
    { field: 'balance', headerName: 'Balance', width: 120 },
    { field: 'courseTitle', headerName: 'Course Title', width: 150 },
    { field: 'receiptGen', headerName: 'Receipt Generated By', width: 180 },
    { field: 'paymentMode', headerName: 'Payment Mode', width: 140 },
    { field: 'paymentStatus', headerName: 'Status', width: 120 },
    { field: 'courseDuration', headerName: 'Duration', width: 100 },
    { field: 'freezingDate', headerName: 'Freezing Date', width: 130 },
    { field: 'date', headerName: 'Date', width: 110 },
    {
      field: 'view',
      headerName: 'View',
      width: 100,
      renderCell: (params) => (
        <Button
          component={Link}
          to={`/install/${params.row._id}/${params.api.getAllRowIds().indexOf(params.id)}/${params.row.nowPaid}/${params.row.totalPaidSoFar}/${params.row.balance}`}
          variant="outlined"
          size="small"
        >
          👁️
        </Button>
      ),
      sortable: false,
      filterable: false,
    },
    {
      field: 'actions',
      headerName: 'Actions',
      width: 100,
      renderCell: (params) => (
        <>
          <IconButton color="primary" onClick={() => onEdit(params.row)}>
            <Edit />
          </IconButton>
          <IconButton color="error" onClick={() => onDelete(params.row._id)}>
            <Delete />
          </IconButton>
        </>
      ),
      sortable: false,
      filterable: false,
    },
  ];

  // Step 3: Transform data for DataGrid rows
  const rows = flattenedPayments.map((p) => ({
    id: p._id,
    _id: p._id,
    studentRedId: p.register?.student?.studentRedId,
    studentName: p.register?.student?.studentName,
    studentImage: p.register?.student?.studentImage,
    courseFees: p.courseFees,
    alreadyPaid: p.alreadyPaid,
    nowPaid: p.nowPaid,
    totalPaidSoFar: p.totalPaidSoFar,
    balance: p.balance,
    courseTitle: p.register?.course?.courseName,
    receiptGen: p.receiptGen,
    paymentMode: p.paymentMode || p.paymentType || p.register?.paymentType,
    paymentStatus: p.paymentStatus || 'unpaid',
    courseDuration: p.register?.courseDuration,
    freezingDate: p.register?.freezingDate,
    date: p.updatedAt?.slice(0, 10),
  }));

  return (
    <Paper sx={{ height: 600, width: '100%' }}>
      <DataGrid
        rows={rows}
        columns={columns}
        pageSizeOptions={[5, 10, 25, 50, 100]}
        initialState={{
          pagination: {
            paginationModel: { pageSize: 5, page: 0 },
          },
        }}
        disableRowSelectionOnClick
      />
    </Paper>
  );
};

export default StuInsTable;

