// import React from 'react';
// import { Link } from 'react-router-dom';

// const StuRegTable = ({ stuRegs, onEdit, onDelete }) => {
//     console.log('student Regs');
//     console.log(stuRegs);
    
    
//   return (
//     <div className='staff-table-container'>
//       <table className='staff-table'>
//         <thead>
//           <tr>
//             <th>Bill Id</th>
//             <th>Student Id</th>
//             <th>Course Fees</th>   
//             <th>Payment Mode</th>
//             <th>Received Amount</th>
//             <th>Course Title</th>
//             <th>Receipt Generated By</th>  
//             <th>Balance Amount</th>    
//             <th>Duration</th>
//             <th>Freezing Date</th>
//             <th>First Installment</th>
//             <th>View</th>
//             <th>Actions</th>
//           </tr>
//         </thead>
//         <tbody>
//           {stuRegs.map((p, i) => (
//             <tr key={p._id}>
//               <td>{i+1}</td>
//               <td>{p.student?.studentRedId}</td>
//               <td>{p.courseFees}</td>
//               <td>{p.paymentType}</td>
//               <td>{p.amountReceivedd}</td>
//               <td>{p.course?.courseName}</td>
//               <td>{p.receiptGen}</td>
//               <td>{p.balanced}</td>
//               <td>{p.courseDuration}</td>
//                <td>{p.freezingDate}</td>
//                <td>{p.updatedAt?.slice(0,10)}</td>
             
//               <td>
//                    <Link to={`/stureg/${p._id}/${i}`}>👁️</Link>
//               </td>
             
//               <td style={{display: 'flex', justifyContent:'center', alignItems: 'center'}}>
//                 <button onClick={() => onEdit(p)}>✏️</button>
//                 <button onClick={() => onDelete(p._id)}>🗑️</button>
                
//               </td>
//             </tr>
//           ))}
//         </tbody>
//       </table>
//     </div>
//   );
// };

// export default StuRegTable;


import * as React from 'react';
import { DataGrid } from '@mui/x-data-grid';
import {
  IconButton,
  Button,
  Paper
} from '@mui/material';
import { Edit, Delete } from '@mui/icons-material';
import { Link } from 'react-router-dom';

const StuRegTable = ({ stuRegs, onEdit, onDelete }) => {
  const columns = [
    {
      field: 'sno',
      headerName: 'Bill Id',
      width: 80,
      renderCell: (params) => params.api.getAllRowIds().indexOf(params.id) + 1,
      sortable: false,
      filterable: false,
    },
    { field: 'studentRedId', headerName: 'Student Id', width: 130 },
    { field: 'courseFees', headerName: 'Course Fees', width: 120 },
    { field: 'paymentType', headerName: 'Payment Mode', width: 140 },
    { field: 'amountReceivedd', headerName: 'Received Amount', width: 150 },
    { field: 'courseTitle', headerName: 'Course Title', width: 160 },
    { field: 'receiptGen', headerName: 'Receipt Generated By', width: 180 },
    { field: 'balanced', headerName: 'Balance Amount', width: 150 },
    { field: 'courseDuration', headerName: 'Duration', width: 120 },
    { field: 'freezingDate', headerName: 'Freezing Date', width: 130 },
    { field: 'date', headerName: 'First Installment', width: 150 },
    {
      field: 'view',
      headerName: 'View',
      width: 100,
      renderCell: (params) => (
        <Button
          component={Link}
          to={`/stureg/${params.row._id}/${params.api.getAllRowIds().indexOf(params.id)}`}
          variant="outlined"
          size="small"
        >
          👁️
        </Button>
      ),
      sortable: false,
      filterable: false,
    },
    {
      field: 'actions',
      headerName: 'Actions',
      width: 100,
      renderCell: (params) => (
        <>
          <IconButton color="primary" onClick={() => onEdit(params.row)}>
            <Edit />
          </IconButton>
          <IconButton color="error" onClick={() => onDelete(params.row._id)}>
            <Delete />
          </IconButton>
        </>
      ),
      sortable: false,
      filterable: false,
    },
  ];

  const rows = stuRegs.map((p) => ({
    id: p._id,
    _id: p._id,
    studentRedId: p.student?.studentRedId,
    courseFees: p.courseFees,
    paymentType: p.paymentType,
    amountReceivedd: p.amountReceivedd,
    courseTitle: p.course?.courseName,
    receiptGen: p.receiptGen,
    balanced: p.balanced,
    courseDuration: p.courseDuration,
    freezingDate: p.freezingDate,
    date: p.updatedAt?.slice(0, 10),
  }));

  return (
    <Paper sx={{ height: 500, width: '100%' }}>
      <DataGrid
        rows={rows}
        columns={columns}
        pageSizeOptions={[5, 10, 25, 50, 100]}
        initialState={{
          pagination: {
            paginationModel: { pageSize: 5, page: 0 },
          },
        }}
        disableRowSelectionOnClick
      />
    </Paper>
  );
};

export default StuRegTable;

