import React, { useEffect, useState, useRef, useCallback } from "react";
import { useParams } from "react-router-dom";
import { cusToast } from "../../Components/Toast/CusToast";
import './ReceiptPage.css'
import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";
import logo from '../../Assets/Images/logo png.png';
import MainLayout from "../../MainLayout.js/MainLayout";
import apiClient from "../../lib/apiClient";


function StuRegDetails() {
  const { id, index } = useParams();
  const [registeredStudent, setRegisteredStudent] = useState(null);
  const certRef = useRef();

  const getRegisteredStudentById = useCallback(async () => {
    try {
      const res = await apiClient.get(`/api/stureg/${id}/`);
      setRegisteredStudent(res.data?.data || res.data);
    } catch (error) {
      console.log(`Can't fetch student details with id ${id}`, error);
      cusToast("can't fetch student detail", "error");
    }
  }, [id]);

  useEffect(() => {
    getRegisteredStudentById();
  }, [getRegisteredStudentById]);




const downloadPDF = async () => {
  const input = certRef.current;

  try {
    // 1. Capture with scale = 2 for better quality + performance
    const canvas = await html2canvas(input, {
      scale: 2,
      useCORS: true,
      backgroundColor: "#ffffff",
      logging: false,
    });

    // 2. Convert canvas to Blob instead of base64 (faster)
    const canvasBlob = await new Promise((resolve) => canvas.toBlob(resolve, "image/png"));

    // 3. Convert Blob to base64 for jsPDF
    const imgData = await blobToBase64(canvasBlob);

    // 4. Create A4 size PDF & calculate scaled dimensions
    const pdf = new jsPDF("p", "mm", "a4");
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const imgWidth = canvas.width;
    const imgHeight = canvas.height;
    const ratio = Math.min(pageWidth / imgWidth, pageHeight / imgHeight);

    const pdfWidth = imgWidth * ratio;
    const pdfHeight = imgHeight * ratio;

    // 5. Add image to PDF
    pdf.addImage(imgData, "PNG", 0, 0, pdfWidth, pdfHeight);

    // 6. Export PDF blob for upload
    const pdfBlob = await pdf.output("blob");

    // 7. Prepare FormData for backend email upload
    const formData = new FormData();
    formData.append("receipt", pdfBlob, `${registeredStudent.student?.studentName}_receipt.pdf`);
    formData.append("email", registeredStudent.student?.studentMail);
    formData.append("message", `Dear ${registeredStudent.student?.studentName}, please find your receipt from Scope Tech.`);

    // 8. Upload & save PDF in parallel
    await Promise.all([
      apiClient.post('/api/receipt/', formData, {
        headers: { "Content-Type": "multipart/form-data" },
      }),
      pdf.save(`${registeredStudent.student?.studentName}_receipt.pdf`)
    ]);
 cusToast("Receipt sent to email!", "success");
    // 9. WhatsApp message construction
    const phone = '91' + registeredStudent.student?.studentMobile;
    const balance = Number(registeredStudent.courseFees) - Number(registeredStudent.amountReceived);
    const paymentType = balance === 0 ? "Ready Cash" : "Installment";
 
    const message = `
📄 *Scope Tech Software Solution - Receipt*

📍 16/1 Kalki Bhavanam First Floor, Visuvasapuri 4th Street, Arappalayam, Madurai 625016
📞 6383406578 | 9600936470
📧 scopetechsoftwaresolution@gmail.com

----------------------------------------
🧑 Student Name: ${registeredStudent.student?.studentName}
🧾 Receipt No: ${Number(index) + 1}
📅 Receipt Date: ${registeredStudent.updatedAt?.slice(0, 10)}
👨‍🏫 Course Coordinator: ${registeredStudent.staff?.staffName}

🎓 Course Title: ${registeredStudent.course?.courseName}
💰 Course Fees: ₹${registeredStudent.courseFees}
💵 Received Amount: ₹${registeredStudent.amountReceived}
💳 Payment Type: ${paymentType}
💱 Mode of Payment: ${registeredStudent.paymentType}
📌 Receipt Generated By: ${registeredStudent.receiptGen}
⏳ Course Duration: ${registeredStudent.courseDuration}
🧮 Balance Payable: ₹${balance}
----------------------------------------

This is a computer generated receipt, no signature required.
`;

    const encodedMessage = encodeURIComponent(message);
    const waUrlWeb = `https://web.whatsapp.com/send?phone=${phone}&text=${encodedMessage}`;
    window.open(waUrlWeb, "_blank");

  

  } catch (error) {
    console.error("Error sending receipt:", error);
    cusToast("Failed to send receipt!", "error");
  }
};

// Utility to convert Blob to base64
const blobToBase64 = (blob) => {
  return new Promise((resolve) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result);
    reader.readAsDataURL(blob);
  });
};



  if (!registeredStudent) return "Loading...";

  return (
    <MainLayout>
    <div className="container border">
      <div className="details-container  ">
        <div>

         
       

   <div className="receipt-container " ref={certRef}>
            <div className="receipt-box">

              <div className="ImageLayout"></div>
               <div class="strip s2">
                <div class="blue"></div>
                <div class="white white2 left24"></div>
                <div class="blue yellow"></div>
                </div>

                <div className="receipt-front">

                <div >
                
                <div style={{ textAlign: 'center', margin: "20px 0px", }}> <img src={logo} alt="logo" className="logo" /></div>
                <p><strong>Receipt No: </strong> <span>{Number(index) + 1}</span></p>
                </div>

                <div>
                  <h1>RECEIPT</h1>
                   <p className="sub-heading"> 6383406578 | 9600936470 <br />
                scopetechsoftwaresolution@gmail.com</p>
                </div>

                <div>
                  <h3 style={{fontSize: "14px", textAlign: "right"}}>Scope Tech Software Solution</h3>
                   <p  style={{fontSize: "14px", textAlign: "right"}}>
                16/1 Kalki Bhavanam First Floor,
                Visuvasapuri 4th Street, Arappalayam, Madurai 625016
              </p>
               <p  style={{fontSize: "14px", textAlign: "right"}}><strong>Date: </strong> <span>{registeredStudent.updatedAt?.slice(0, 10)}</span></p>
                </div>
               </div>

               

                <div style={{ textAlign: "center", display: "flex", justifyContent: 'center', height: "5px"}}>
                 <div className="strip2"></div>
                </div>


            
               <div className="dflex" style={{flexDirection: 'row', padding: "40px 0px"}}>
             

              <table className="billtable">
                <tbody>
                  <tr>

                    <td>

                      <strong>Student Name:</strong>
                    </td>
                    <td>{registeredStudent.student?.studentName}</td>
                     <td>

                      <strong>Course Coordinator:</strong>
                    </td>
                    <td>{registeredStudent.staff?.staffName}</td>
                  </tr>
                  
                  <tr>


                    <td>
                      <strong>Course Title:</strong>
                    </td>
                    <td>{registeredStudent.course?.courseName}</td>
                    <td>

                      <strong>Course Fees:</strong>
                    </td>
                    <td>{registeredStudent.courseFees}</td>
                  </tr>
                  <tr>


                    <td>
                      <strong>Type of Payment</strong>
                    </td>
                    <td>{Number(registeredStudent.courseFees) - Number(registeredStudent.amountReceived) === 0 ? 'Ready Cash' : 'Installment'}</td>
                    <td>

                      <strong>Received Amount</strong>
                    </td>
                    <td>{registeredStudent.amountReceived}</td>
                  </tr>
                  <tr>


                    <td>
                      <strong>Mode of Payment</strong>
                    </td>
                    <td>{registeredStudent.paymentType}</td>
                    <td>

                      <strong>Receipt generated by</strong>
                    </td>
                    <td>{registeredStudent.receiptGen}</td>
                  </tr>
                  <tr>


                    <td>
                      <strong>Balance Payable</strong>
                    </td>
                    <td>{Number(registeredStudent.courseFees) - Number(registeredStudent.amountReceived)}</td>
                    <td>

                      <strong>Course Duration</strong>
                    </td>
                    <td>{registeredStudent.courseDuration}</td>
                  </tr>
                </tbody>
              </table></div>

              {
                Number(registeredStudent.courseFees) - Number(registeredStudent.amountReceived) === 0 ? "" : (
  <div  style={{display: "flex", justifyContent: 'space-between', alignItems: 'center', padding: '0px 20px'}}>
              <p> <strong>Second Installment Date:</strong> {registeredStudent.secondInstallment}</p>
              <p> <strong>Penalty per day Rs.10</strong> </p>
             </div>

                )
              }

           
              <p className="mt-10">
                <strong>Receipt Details Email To:</strong> {registeredStudent.student?.studentMail}
              </p>
              <p className="note">
                This is a computer generated bill, hence signature not required.
              </p>
                <div class="strip s1 ">
                <div class="blue yellow"></div>
                <div class="white white2 parrallel right24"></div>
                <div class="blue "></div>
                </div>
            </div>
          </div>


          {/* Download Button */}
          <div style={{ textAlign: "center", marginTop: "20px" }}>
            <button
              style={{
                padding: "10px 20px",
                backgroundColor: "#4CAF50",
                color: "white",
                border: "none",
                borderRadius: "5px",
                cursor: "pointer",
              }} onClick={downloadPDF}
            >
              send Mail
            </button>
          </div>
        </div>
      </div>
    </div>
    </MainLayout>
  );
}

export default StuRegDetails;
