import React, { useEffect, useState, useRef, useCallback } from "react";
import { useParams } from "react-router-dom";
import { cusToast } from "../../Components/Toast/CusToast";
import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";
import logo from '../../Assets/Images/logo png.png';
import MainLayout from "../../MainLayout.js/MainLayout";
import apiClient from "../../lib/apiClient";
function StuInsDetails() {
  const { id, index, nowpaid, total, balance } = useParams();
  const [installedStudent, setInstalledStudent] = useState(null);
  const certRef = useRef();
  const [isLoading, setIsLoading] = useState(false);
  const [iswLoading, setIswLoading] = useState(false);

  const getRegisteredStudentById = useCallback(async () => {
    try {
      const res = await apiClient.get(`/api/stuins/${id}/`);
      setInstalledStudent(res.data);
    } catch (error) {
      console.log(`Can't fetch student details with id ${id}`, error);
      cusToast("can't fetch student detail", "error");
    }
  }, [id]);

  useEffect(() => {
    getRegisteredStudentById();
  }, [getRegisteredStudentById]);




const downloadPDF = async () => {
    setIsLoading(true);
  const input = certRef.current;

  try {
    // 1. Capture with scale = 2 for better quality + performance
    const canvas = await html2canvas(input, {
      scale: 2,
      useCORS: true,
      backgroundColor: "#ffffff",
      logging: false,
    });

    // 2. Convert canvas to Blob instead of base64 (faster)
    const canvasBlob = await new Promise((resolve) => canvas.toBlob(resolve, "image/png"));

    // 3. Convert Blob to base64 for jsPDF
    const imgData = await blobToBase64(canvasBlob);

    // 4. Create A4 size PDF & calculate scaled dimensions
    const pdf = new jsPDF("p", "mm", "a4");
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const imgWidth = canvas.width;
    const imgHeight = canvas.height;
    const ratio = Math.min(pageWidth / imgWidth, pageHeight / imgHeight);

    const pdfWidth = imgWidth * ratio;
    const pdfHeight = imgHeight * ratio;

    // 5. Add image to PDF
    pdf.addImage(imgData, "PNG", 0, 0, pdfWidth, pdfHeight);

    // 6. Export PDF blob for upload
    const pdfBlob = await pdf.output("blob");

    // 7. Prepare FormData for backend email upload
    const formData = new FormData();
    formData.append("receipt", pdfBlob, `${installedStudent.register?.student?.studentName}_receipt.pdf`);
    formData.append("email", installedStudent.register?.student?.studentMail);
    formData.append("message", `Dear ${installedStudent.register?.student?.studentName}, please find your receipt from Scope Tech.`);

    // 8. Upload & save PDF in parallel
    await Promise.all([
      apiClient.post('/api/receipt/', formData, {
        headers: { "Content-Type": "multipart/form-data" },
      }),
      pdf.save(`${installedStudent.register?.student?.studentName}_receipt.pdf`)
    ]);
 cusToast("Receipt sent to email!", "success");
    // 9. WhatsApp message construction
   

  setIsLoading(false);

  } catch (error) {
    console.error("Error sending receipt:", error);
    cusToast("Failed to send receipt!", "error");
  }
};

const sendWhatsapp = () => {
    setIswLoading(true);
    // const fileUrl = `${API}/uploads/${res.data.fileName}`;
    const phone = '91' + installedStudent.register?.student?.studentMobile;
    const balance = installedStudent.register?.balance;
    const paymentType = balance === 0 ? "Ready Cash" : "Installment";
 
    const message = `
📄 *Scope Tech Software Solution - Receipt*

📍 16/1 Kalki Bhavanam First Floor, Visuvasapuri 4th Street, Arappalayam, Madurai 625016
📞 6383406578 | 9600936470
📧 scopetechsoftwaresolution@gmail.com

----------------------------------------
🧑 Student Name: ${installedStudent.register?.student?.studentName}
🧾 Receipt No: ${Number(index) + 1}
📅 Receipt Date: ${installedStudent.register?.updatedAt?.slice(0, 10)}
👨‍🏫 Course Coordinator: ${installedStudent.register?.staff?.staffName}

🎓 Course Title: ${installedStudent.register?.course?.courseName}
💰 Course Fees: ₹${installedStudent.register?.courseFees}
💵 Received Amount: ₹${nowpaid}
💵 Total Received Amount: ₹${total}
💳 Payment Type: ${paymentType}
💱 Mode of Payment: ${installedStudent.register?.paymentType}
📌 Receipt Generated By: ${installedStudent.register?.receiptGen}
⏳ Course Duration: ${installedStudent.register?.courseDuration}
🧮 Balance Payable: ₹${balance}
----------------------------------------

This is a computer generated receipt, no signature required.
`;

    const encodedMessage = encodeURIComponent(message);
    const waUrlWeb = `https://web.whatsapp.com/send?phone=${phone}&text=${encodedMessage}`;
    window.open(waUrlWeb, "_blank");
    setIswLoading(false);
}

// Utility to convert Blob to base64
const blobToBase64 = (blob) => {
  return new Promise((resolve) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result);
    reader.readAsDataURL(blob);
  });
};

const calculatePenalty = () => {
  if (!installedStudent?.nextIns) return 0;

  const nextDate = new Date(installedStudent.nextIns);
  const today = new Date();

  // Only calculate penalty if today > next installment date
  if (today > nextDate) {
    const diffTime = today - nextDate; // in ms
    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
    return diffDays * 10; // ₹10 per day
  }
  return 0;
};


  if (!installedStudent) return "Loading...";

  return (
    <MainLayout>
    <div className="container border">
      <div className="details-container  ">
        <div>

         
       

   <div className="receipt-container " ref={certRef}>
            <div className="receipt-box">

              <div className="ImageLayout"></div>
               <div class="strip s2">
                <div class="blue"></div>
                <div class="white white2 left24"></div>
                <div class="blue yellow"></div>
                </div>

                <div className="receipt-front">

                <div >
                
                <div style={{ textAlign: 'center', margin: "20px 0px", }}> <img src={logo} alt="logo" className="logo" /></div>
                <p><strong>Receipt No: </strong> <span>{Number(index) + 1}</span></p>
                </div>

                <div>
                  <h1>RECEIPT</h1>
                   <p className="sub-heading"> 6383406578 | 9600936470 <br />
                scopetechsoftwaresolution@gmail.com</p>
                </div>

                <div>
                  <h3 style={{fontSize: "14px", textAlign: "right"}}>Scope Tech Software Solution</h3>
                   <p  style={{fontSize: "14px", textAlign: "right"}}>
                16/1 Kalki Bhavanam First Floor,
                Visuvasapuri 4th Street, Arappalayam, Madurai 625016
              </p>
               <p  style={{fontSize: "14px", textAlign: "right"}}><strong>Date: </strong> <span>{installedStudent.updatedAt?.slice(0, 10)}</span></p>
                </div>
               </div>

               

                <div style={{ textAlign: "center", display: "flex", justifyContent: 'center', height: "5px"}}>
                 <div className="strip2"></div>
                </div>


            
               <div className="dflex" style={{flexDirection: 'row', padding: "40px 0px"}}>
             

              <table className="billtable">
                <tbody>
                  <tr>

                    <td>

                      <strong>Student Name:</strong>
                    </td>
                    <td>{installedStudent.register?.student?.studentName}</td>
                     <td>

                      <strong>Course Coordinator:</strong>
                    </td>
                    <td>{installedStudent.register?.staff?.staffName}</td>
                  </tr>
                  
                  <tr>


                    <td>
                      <strong>Course Title:</strong>
                    </td>
                    <td>{installedStudent.register?.course?.courseName}</td>
                    <td>

                      <strong>Course Fees:</strong>
                    </td>
                    <td>{installedStudent.register?.courseFees}</td>
                  </tr>
                  <tr>


                    <td>

                      <strong>Received Amount</strong>
                    </td>
                    <td>{nowpaid}</td>
                    <td>

                      <strong>Total  Amount Received</strong>
                    </td>
                    <td>{total}</td>
                  </tr>
                 
                  <tr>

                    <td>
                      <strong>Mode of Payment</strong>
                    </td>
                    <td>{installedStudent.paymentType}</td>
                    <td>

                      <strong>Receipt generated by</strong>
                    </td>
                    <td>{installedStudent.receiptGen}</td>
                  </tr>
                  <tr>


                    <td>
                      <strong>Balance Payable</strong>
                    </td>
                    <td>{balance}</td>
                    <td>

                      <strong>Course Duration</strong>
                    </td>
                    <td>{installedStudent.register?.courseDuration}</td>
                  </tr>
                </tbody>
              </table></div>

          {
  Number(installedStudent.register?.balance) === 0 ? null : (
    <div style={{display: "flex", justifyContent: 'space-between', alignItems: 'center', padding: '0px 20px'}}>
      <p><strong>Next Installment Date:</strong> {installedStudent.nextIns?.slice(0, 10)}</p>
      {
        calculatePenalty() > 0 ? (
          <p><strong>Penalty: ₹{calculatePenalty()}</strong></p>
        ) : (
          <p><strong>Penalty per day ₹10</strong></p>
        )
      }
    </div>
  )
}


           
              <p className="mt-10">
                <strong>Receipt Details Email To:</strong> {installedStudent.student?.studentMail}
              </p>
              <p className="note">
                This is a computer generated bill, hence signature not required.
              </p>
                <div class="strip s1 ">
                <div class="blue yellow"></div>
                <div class="white white2 parrallel right24"></div>
                <div class="blue "></div>
                </div>
            </div>
          </div>


          {/* Download Button */}
          <div style={{ textAlign: "center", marginTop: "20px" }}>
            <button
              style={{
                padding: "10px 20px",
                backgroundColor: "#4CAF50",
                color: "white",
                border: "none",
                borderRadius: "5px",
                cursor: isLoading ? "not-allowed" : "pointer",
    opacity: isLoading ? 0.6 : 1,
              }} onClick={downloadPDF}
            >
              {isLoading ? 'sending Mail...' : 'Send Mail'}
            </button>
             <button
              style={{
                padding: "10px 20px",
                backgroundColor: "#4CAF50",
                color: "white",
                border: "none",
                borderRadius: "5px",
               
                 cursor: iswLoading ? "not-allowed" : "pointer",
    opacity: iswLoading ? 0.6 : 1,
              }} onClick={sendWhatsapp}
            >
              {iswLoading ? 'sending whatsapp...' : 'Send whatsapp'}
            </button>
          </div>
        </div>
      </div>
    </div>
    </MainLayout>
  );
}

export default StuInsDetails;
